idci_keycloak_security_auth_connect:
    path:       /auth/connect/keycloak
    controller: IDCI\Bundle\KeycloakSecurityBundle\Controller\KeycloakController::connect

idci_keycloak_security_auth_connect_check:
    path:       /auth/connect-check/keycloak
    controller: IDCI\Bundle\KeycloakSecurityBundle\Controller\KeycloakController::connectCheck

idci_keycloak_security_auth_logout:
    path:       /auth/logout
    controller: IDCI\Bundle\KeycloakSecurityBundle\Controller\KeycloakController::logout

idci_keycloak_security_auth_account:
    path:       /auth/account
    controller: IDCI\Bundle\KeycloakSecurityBundle\Controller\KeycloakController::account
