security:
    providers:
        idci_keycloak_security_provider:
            id: IDCI\Bundle\KeycloakSecurityBundle\Security\User\KeycloakUserProvider
        idci_keycloak_bearer_security_provider:
            id: IDCI\Bundle\KeycloakSecurityBundle\Security\User\KeycloakBearerUserProvider
